#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
#$HOME/.config/polybar-themes/launch.sh  --colorblocks
$HOME/.config/polybar/launch.sh

# compositing and wallpaper
if ps -A | grep picom; then
	killall -q picom
fi
~/src/picom/build/src/picom &

feh --no-fehbg --bg-scale $HOME/wallpapers/forest.jpg


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          0
bspc config window_gap            20

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monacle       true

bspc config focused_border_color  "#83a598"
bspc config normal_border_color   "#454849"
bspc config presel_feedback_color "#ffffff"

#bspc rule -a program desktop='^0' state=floating follow=on focus=on manage=off
bspc rule -a discord desktop='^10'
bspc rule -a spotify desktop='^9'



# Fix cursor default
xsetroot -cursor_name left_ptr &

# Fix issue with some apps
wmname LG3D


# Start-up applications/scripts
# ./scripts/welcome/welcome.py
