#!/bin/sh

#    _                                 
#   | |__  ___ _ ____      ___ __ ___  
#   | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#  _| |_) \__ \ |_) \ V  V /| | | | | |
# (_)_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#             |_|                      
#
# Configuration for bspwm
# [Binary space partitionaing window manager]
#

# Start pipewire
# (audio)
pipewire &
pipewire-pulse &
# do i need this?
#wireplumber &

# Start sxhkd if not already started
# (keyboard)
pgrep -x sxhkd > /dev/null || sxhkd &

# Restart picom if started or just start
# (compositor)
[[ $(pgrep -x picom) ]] && kill $(pgrep -x picom)
picom &

# Set wallpaper
#feh --no-fehbg --bg-scale $HOME/Pictures/Wallpapers/forest_mountain.jpg
feh --no-fehbg --bg-scale $HOME/Pictures/Wallpapers/desat_forest_mountain.jpg
#feh --no-fehbg --bg-scale $HOME/Pictures/Wallpapers/Variants/1.png
#feh --no-fehbg --bg-scale $HOME/Pictures/Wallpapers/Variants/2.png

# Start eww
$HOME/.local/bin/eww open bar &

$HOME/.config/bspwm/scripts/eww_fullscreen_fix.sh &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config left_padding		50
bspc config window_gap			20

bspc config split_ratio			0.50

bspc config borderless_monocle		true
bspc config gapless_monocle		true

# Border colors
bspc config focused_border_color	"#ff0000"
bspc config normal_border_color		"#00ff00"
bspc config presel_feedback_color	"#0000ff"

# Window rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Fix cursor default
xsetroot -cursor_name left_ptr &

# Fix issue with some apps
wmname LG3d
